name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: mohamedgaber353/nodjs

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.run_number }} .

      # Step 3: Login to DockerHub
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 4: Push Docker image to DockerHub
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ github.run_number }}

      # Step 5: Deploy Application to EC2
      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > ec2-key.pem
          chmod 400 ec2-key.pem
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@ec2-52-73-65-200.compute-1.amazonaws.com << EOF
            docker rm -f gaber || true
            docker run -d --name gaber -p 3050:3000 $IMAGE_NAME:${{ github.run_number }}
            docker container prune -f
          EOF
